server:
  port: 8080 #\u914D\u7F6E\u7AEF\u53E3\u53F7
  servlet:
    context-path: /appinfo #\u9879\u76EE\u7684\u8BBF\u95EE\u540D\u79F0
spring:
  mvc:
    static-path-pattern: /static/** #\u9879\u76EE\u7684\u9759\u6001\u8D44\u6E90
    servlet:
      load-on-startup: 1
  resources:
    static-locations: classpath:/static/
  datasource: #\u6570\u636E\u6E90 \u7528\u4E8E\u7BA1\u7406\u6570\u636E\u5E93\u7684\u94FE\u63A5
    #\u94FE\u63A5\u5B57\u7B26\u4E32
    url: jdbc:mysql://localhost:3306/appinfodb?serverTimezone=UTC&userUnicode=true&charaterEncode=utf8&userSSL=false
    #\u6570\u636E\u5E93\u7684\u8D26\u53F7
    username: root
    #\u6570\u636E\u5E93\u7684\u5BC6\u7801
    password: 123456
    #\u6570\u636E\u5E93\u7684\u9A71\u52A8\u7C7B
    driver-class-name: com.mysql.jdbc.Driver
    #\u6570\u636E\u6E90\u7684\u7C7B\u578B
    type: com.alibaba.druid.pool.DruidDataSource
    #\u521D\u59CB\u5316 \u8FDE\u63A5\u7684\u6570\u91CF
    initial-size: 5
    # \u6700\u5C0F\u503C
    min-idle: 5
    # \u6700\u5927\u503C
    max-active: 20
    # \u6700\u5927\u7B49\u5230\u65F6\u95F4\uFF0C\u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u8FC7\u7684\u65F6\u95F4
    max-wait: 60000
    # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u68C0\u6D4B\u4E00\u6B21\u8FDE\u63A5\uFF0C\u5173\u95ED\u4E0D\u9700\u8981\u7684\u7A7A\u95F2\u8FDE\u63A5
    time-between-eviction-runs-millis: 60000
    # \u914D\u7F6E \u8FDE\u63A5\u5728\u8FDE\u63A5\u6C60\u4E2D\u6700\u5C0F\u7684\u751F\u5B58\u65F6\u95F4
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j2
    use-global-data-source-stat: true
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    thymeleaf: # \u914D\u7F6E \u89C6\u56FE\u8DEF\u5F84\u9875\u9762
      servlet:
        content-type: text/html
      cache: false #\u662F\u5426\u7F13\u5B58\u9875\u9762\uFF0C\u5F00\u53D1\u73AF\u5883\u4E0B\u53CA\u65F6\u7684\u5237\u65B0
      encoding: UTF-8
      mode: LEGACYHTML5
      prefix: classpath:/templates/
      suffix: .html
      check-template-location: false
  servlet: # \u6587\u4EF6\u4E0A\u4F20\u65F6\u8981\u7528\u7684\u914D\u7F6E
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  freemarker:
    cache: false # \u9875\u9762\u4E0D\u52A0\u8F7D\u7F13\u5B58 \u4FEE\u6539\u540E\u7ACB\u5373\u751F\u6548
mybatis: # MyBatis \u914D\u7F6E
  type-aliases-package: com.xk.pojo # \u522B\u540D
  mapper-locations: classpath:mapper/*.xml # \u6620\u5C04\u6587\u4EF6\u7684\u8DEF\u5F84
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # \u65E5\u5FD7 \u5C55\u793Asql\u8BED\u53E5